// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  linuxTutorialSidebar: [{type: 'autogenerated', dirName: 'linux'}],
  debianTutorialSidebar:[
    {type: 'doc',label: 'intro',id:"debian/intro"},
    {
      type: 'category',
      label: '1. úvod',
      items: [
        {type: 'doc',label: 'instalační soubor',id:"debian/uvod/instalacni_soubor"},
        {type: 'doc',label: 'instalace',id:"debian/uvod/instalace_uvod_basic"},
        {type: 'doc',label: 'instalace-bookworm',id:"debian/uvod/instalace_uvod_bookworm"},
        {type: 'doc',label: 'neofetch',id:"debian/uvod/neofetch"}
      ],
    },
    {
      type: 'category',
      label: 'x. procesy',
      items: [
        {type: 'doc',label: 'cron',id:"debian/procesy/cron"},
      ],
    },
    {
      type: 'category',
      label: 'x. bash',
      items: [
        {type: 'doc',label: 'intro',id:"debian/bash/intro"},
      ],
    },
    {
      type: 'category',
      label: 'x. ricing',
      items: [
        {type: 'doc',label: 'desktop enviroment',id:"debian/ricing/enviroment"},
        {type: 'doc',label: 'KDE Plasma',id:"debian/ricing/kde_plasma"}
      ],
    },
    {
      type: 'category',
      label: 'x. databáze',
      items: [
        {type: 'doc',label: 'MySQL',id:"debian/databaze/MySQL"},
        {type: 'doc',label: 'MongoDB',id:"debian/databaze/MongoDB"},
      ],
    },


  ],
  rustTutorialSidebar: [{type: 'autogenerated', dirName: 'rust'}],
  typeScriptTutorialSidebar:[
    'typescript/intro',
    {
      type: 'category',
      label: '1. úvod',
      items: [
        'typescript/uvod/instalace',
        'typescript/uvod/kompilace'
      ],
    }
  ], 
  angularTutorialSidebar: [{type: 'autogenerated', dirName: 'angular'}],
  cppTutorialSidebar: [{type: 'autogenerated', dirName: 'angular'}],
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Docosaurus',
      items: [{type: 'autogenerated', dirName: 'other/docosaurus'}],
    },
    {
      type: 'category',
      label: 'Tailwind',
      items: ['other/docosaurus/intro'],
    },
    {
      type: 'category',
      label: 'Tailwind',
      items: ['other/docosaurus/intro'],
    },
    {
      type: 'category',
      label: 'MongoDB',
      items: ['other/docosaurus/intro'],
    },
  ],
  techTutorialSidebar: [{type: 'autogenerated', dirName: 'angular'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
