// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  linuxTutorialSidebar: [{type: 'autogenerated', dirName: 'linux'}],
  rustTutorialSidebar: [{type: 'autogenerated', dirName: 'rust'}],
  typeScriptTutorialSidebar:[
    'typescript/intro',
    {
      type: 'category',
      label: '1. úvod',
      items: [
        'typescript/uvod/instalace',
        'typescript/uvod/kompilace'
      ],
    }
  ], 
  angularTutorialSidebar: [{type: 'autogenerated', dirName: 'angular'}],
  cppTutorialSidebar: [{type: 'autogenerated', dirName: 'angular'}],
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Docosaurus',
      items: [{type: 'autogenerated', dirName: 'other/docosaurus'}],
    },
    {
      type: 'category',
      label: 'Tailwind',
      items: ['other/docosaurus/intro'],
    },
    {
      type: 'category',
      label: 'Tailwind',
      items: ['other/docosaurus/intro'],
    },
    {
      type: 'category',
      label: 'MongoDB',
      items: ['other/docosaurus/intro'],
    },
  ],
  techTutorialSidebar: [{type: 'autogenerated', dirName: 'angular'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
